spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soat_modulo_2
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true