springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha

swagger:
  url: ${SWAGGER_URL:}

Spring:
  profiles:
    active: h2

jwt:
  secret: test-secret

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true